name: ranepa_timetable
description: Custom RANEPA android client on Flutter.

version: 1.7+16

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  xml: ^3.4.1
  shared_preferences: ^0.5.1+1
  json_serializable: ^2.0.3
  intro_views_flutter: ^2.4.0
  android_intent: ^0.3.0
  tuple: ^1.0.2
  device_calendar: ^0.1.1
  url_launcher: ^5.0.2
  flutter_svg: ^0.12.0
  duration: ^2.0.4
  flutter_duration_picker:
    git:
      url: git://github.com/aman-malhotra-1999/flutter_duration_picker.git
  auto_size_text: ^1.0.0
  flutter_email_sender: ^2.0.0
  flutter_material_color_picker: ^0.0.5
  package_info: ^0.4.0+2
  flutter_screenutil: ^0.5.1
  flutter_cupertino_date_picker:
    git:
      url: git://github.com/CoolONEOfficial/flutter-cupertino-date-picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  intl_translation: ^0.17.3
  build_runner: ^1.2.8

flutter_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon-foreground.png"

flutter:

  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family:  TimetableIcons
    fonts:
    - asset: assets/fonts/TimetableIcons.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
