name: ranepa_timetable
description: Custom RANEPA android client on Flutter.

version: 1.3.1+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0
  xml: ^3.2.3
  shared_preferences: ^0.4.3
  json_serializable: ^2.0.0
  intro_views_flutter: ^2.4.0
  android_intent: ^0.2.1
  tuple: ^1.0.2
  device_calendar: ^0.0.7
  url_launcher: ^4.1.0+1
  flutter_svg: ^0.8.2
  duration: ^2.0.4
  flutter_duration_picker: ^1.0.4
  auto_size_text: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  intl_translation: ^0.17.1
  build_runner: ^1.0.0

flutter_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon-foreground.png"

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family:  TimetableIcons
     fonts:
      - asset: assets/fonts/TimetableIcons.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
